=== EvanLoaf/testjava/web/src/main/resources/xml/items_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://gmail.com/evanloafakahaitao"
           xmlns="https://gmail.com/evanloafakahaitao"
           elementFormDefault="qualified">
    <xs:element name="store" type="root"/>
    <xs:complexType name="root">
        <xs:sequence>
            <xs:element name="item" type="itemType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="vendorcode" type="vendorcodeType"/>
            <xs:element name="description" type="descriptionType"/>
            <xs:element name="price" type="priceType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]+[a-zA-Z0-9 ]{0,19}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="vendorcodeType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{10}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="descriptionType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]+[a-zA-Z0-9 ]{0,99}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="7"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== EvanLoaf/testjava/web/src/main/resources/xml/items.xml
<?xml version="1.0" encoding="UTF-8"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="https://gmail.com/evanloafakahaitao"
       xsi:schemaLocation="https://gmail.com/evanloafakahaitao items_schema.xsd">
    <item>
        <name>Computer 1</name>
        <vendorcode>0000001001</vendorcode>
        <description>Entry level gaming solution with best price to performance ratio</description>
        <price>499.99</price>
    </item>
    <item>
        <name>Computer 2</name>
        <vendorcode>0000001002</vendorcode>
        <description>Entry level gaming solution with best price to performance ratio</description>
        <price>549.99</price>
    </item>
    <item>
        <name>Computer 3</name>
        <vendorcode>0000002001</vendorcode>
        <description>Optimal pc for fullHD gaming</description>
        <price>799.99</price>
    </item>
    <item>
        <name>Computer 4</name>
        <vendorcode>0000002002</vendorcode>
        <description>Optimal for newest releases in fullHD</description>
        <price>1199.99</price>
    </item>
    <item>
        <name>Computer 5</name>
        <vendorcode>0000002003</vendorcode>
        <description>Buy once and game for years without upgrades</description>
        <price>1299.99</price>
    </item>
    <item>
        <name>Computer 6</name>
        <vendorcode>0000002004</vendorcode>
        <description>Buy once and game for years without upgrades</description>
        <price>1399.99</price>
    </item>
    <item>
        <name>Computer 7</name>
        <vendorcode>0000002005</vendorcode>
        <description>When every single fps can give you an edge</description>
        <price>1499.99</price>
    </item>
    <item>
        <name>Computer 8</name>
        <vendorcode>0000002006</vendorcode>
        <description>Ultimate gaming power with hydro cooling system</description>
        <price>1999.99</price>
    </item>
    <item>
        <name>Computer 9</name>
        <vendorcode>0000003001</vendorcode>
        <description>Professional solution for gpaphics and video editing</description>
        <price>1799.99</price>
    </item>
    <item>
        <name>Computer 10</name>
        <vendorcode>0000003002</vendorcode>
        <description>Professional solution for any purposes and challenges</description>
        <price>4999.99</price>
    </item>
    <item>
        <name>Computer 11</name>
        <vendorcode>0000009000</vendorcode>
        <description>Ultimate workstation for your projects</description>
        <price>14999.99</price>
    </item>
</store>
